# see:
# https://pre-commit.com/#intro
# https://github.com/Lightning-AI/lightning/blob/master/.pre-commit-config.yaml#L70

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: |
          (?x)(
              ^lightning_training_studio/app/ui/build|
              ^lightning_training_studio/app/ui/yarn.lock|
              ^lightning_training_studio/app/ui/src/generated
          )

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Format imports

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Format code
        args: ["--line-length=120"]

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        args: [--line-length=120]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Check PEP8
        args:
          - "--max-line-length=120"
          - "--ignore=E402,E501,F811"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        exclude: |
          (?x)(
              ^lightning_training_studio/app/ui/build|
              README.md|
              ^lightning_training_studio/app/ui/src/generated|
              ^.github|
              ^tests|
              ^docs
          )
        additional_dependencies:
          - prettier@2.7.1
          - typescript@4.4.2
          - prettier-plugin-organize-imports@3.1.0
